server:
  port: 8761
  http2:
    enabled: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  file:
    path: service-discovery/logs
    name: ${logging.file.path}/eureka.log
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    enryu.microservices.servicediscovery: DEBUG
