

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  http2:
    enabled: true
  port: 8111

logging:
  file:
    path: order-service/logs
    name: ${logging.file.path}/order-service.log
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    enryu.microservices.orderservice: DEBUG

broker:
  rabbit:
    queue:
      order: order-queue
      product: product-queue
    exchange:
      topic:
        order: order-exchange
        product: product-exchange
    routing_key:
      order: order-routing-key
      product: product-routing-key
