

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  http2:
    enabled: true
  port: 8111